#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
     resource: '../src/Controller'
     type: annotation
index:
     path: /
     controller: App\Controller\Dashboard::index