#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
     resource: '../src/Controller'
     type: annotation
index:
     path: /
     controller: App\Controller\DashboardController::index

## Projects
project_index:
     path: /projects
     controller: App\Controller\ProjectController::index
project_new:
     path: /project/new
     controller: App\Controller\ProjectController::new
project_details:
     path: /project/details/{id<\d+>}
     controller: App\Controller\ProjectController::detail
project_edit:
     path: /project/edit/{id<\d+>}
     controller: App\Controller\ProjectController::edit
project_book_hours_new:
     path: /project/book-hours
     controller: App\Controller\ProjectHoursController::new
project_book_hours_to_project:
     path: /project/book-hours/{id<\d+>}
     controller: App\Controller\ProjectHoursController::newFromProject
projects_hours_overview:
     path: /projects-hours-overview
     controller: App\Controller\ProjectHoursController::index

## Contacts
contact_index:
     path: /contacts
     controller: App\Controller\ContactController::index
contact_new:
     path: /contact/new
     controller: App\Controller\ContactController::new
contact_edit:
     path: /contact/edit/{id<\d+>}
     controller: App\Controller\ContactController::edit

